//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Language.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LanguageParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LanguageParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDcl([NotNull] LanguageParser.DclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDcl([NotNull] LanguageParser.DclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExplicitVarDcl</c>
	/// labeled alternative in <see cref="LanguageParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitVarDcl([NotNull] LanguageParser.ExplicitVarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExplicitVarDcl</c>
	/// labeled alternative in <see cref="LanguageParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitVarDcl([NotNull] LanguageParser.ExplicitVarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImplicitVarDcl</c>
	/// labeled alternative in <see cref="LanguageParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitVarDcl([NotNull] LanguageParser.ImplicitVarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImplicitVarDcl</c>
	/// labeled alternative in <see cref="LanguageParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitVarDcl([NotNull] LanguageParser.ImplicitVarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InitSlice</c>
	/// labeled alternative in <see cref="LanguageParser.sliceDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitSlice([NotNull] LanguageParser.InitSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InitSlice</c>
	/// labeled alternative in <see cref="LanguageParser.sliceDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitSlice([NotNull] LanguageParser.InitSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareSlice</c>
	/// labeled alternative in <see cref="LanguageParser.sliceDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareSlice([NotNull] LanguageParser.DeclareSliceContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareSlice</c>
	/// labeled alternative in <see cref="LanguageParser.sliceDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareSlice([NotNull] LanguageParser.DeclareSliceContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InitMatrix</c>
	/// labeled alternative in <see cref="LanguageParser.matrixDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitMatrix([NotNull] LanguageParser.InitMatrixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InitMatrix</c>
	/// labeled alternative in <see cref="LanguageParser.matrixDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitMatrix([NotNull] LanguageParser.InitMatrixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.structDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDclInit([NotNull] LanguageParser.StructDclInitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.structDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDclInit([NotNull] LanguageParser.StructDclInitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InstanceStruct</c>
	/// labeled alternative in <see cref="LanguageParser.instStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstanceStruct([NotNull] LanguageParser.InstanceStructContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InstanceStruct</c>
	/// labeled alternative in <see cref="LanguageParser.instStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstanceStruct([NotNull] LanguageParser.InstanceStructContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.functionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDclInit([NotNull] LanguageParser.FunctionDclInitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.functionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDclInit([NotNull] LanguageParser.FunctionDclInitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionStructDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.functionStructDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStructDclInit([NotNull] LanguageParser.FunctionStructDclInitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionStructDclInit</c>
	/// labeled alternative in <see cref="LanguageParser.functionStructDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStructDclInit([NotNull] LanguageParser.FunctionStructDclInitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] LanguageParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] LanguageParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] LanguageParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] LanguageParser.PrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] LanguageParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] LanguageParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] LanguageParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] LanguageParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStmt([NotNull] LanguageParser.SwitchStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStmt([NotNull] LanguageParser.SwitchStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStmtSimple</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmtSimple([NotNull] LanguageParser.ForStmtSimpleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStmtSimple</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmtSimple([NotNull] LanguageParser.ForStmtSimpleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStmtComplex</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmtComplex([NotNull] LanguageParser.ForStmtComplexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStmtComplex</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmtComplex([NotNull] LanguageParser.ForStmtComplexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ForStmtRange</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmtRange([NotNull] LanguageParser.ForStmtRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ForStmtRange</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmtRange([NotNull] LanguageParser.ForStmtRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStmt([NotNull] LanguageParser.BreakStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStmt([NotNull] LanguageParser.BreakStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStmt([NotNull] LanguageParser.ContinueStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStmt([NotNull] LanguageParser.ContinueStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] LanguageParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="LanguageParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] LanguageParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] LanguageParser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] LanguageParser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] LanguageParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] LanguageParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.matrixargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrixargs([NotNull] LanguageParser.MatrixargsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.matrixargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrixargs([NotNull] LanguageParser.MatrixargsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.atributos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtributos([NotNull] LanguageParser.AtributosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.atributos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtributos([NotNull] LanguageParser.AtributosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.argsA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgsA([NotNull] LanguageParser.ArgsAContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.argsA"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgsA([NotNull] LanguageParser.ArgsAContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseBlock([NotNull] LanguageParser.CaseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseBlock([NotNull] LanguageParser.CaseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultBlock([NotNull] LanguageParser.DefaultBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.defaultBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultBlock([NotNull] LanguageParser.DefaultBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructItemAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructItemAssign([NotNull] LanguageParser.StructItemAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructItemAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructItemAssign([NotNull] LanguageParser.StructItemAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ItemMatrixAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemMatrixAssign([NotNull] LanguageParser.ItemMatrixAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ItemMatrixAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemMatrixAssign([NotNull] LanguageParser.ItemMatrixAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceJoin</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceJoin([NotNull] LanguageParser.SliceJoinContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceJoin</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceJoin([NotNull] LanguageParser.SliceJoinContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ItemAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItemAssign([NotNull] LanguageParser.ItemAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ItemAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItemAssign([NotNull] LanguageParser.ItemAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StringToInt</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringToInt([NotNull] LanguageParser.StringToIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringToInt</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringToInt([NotNull] LanguageParser.StringToIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParens([NotNull] LanguageParser.ParensContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParens([NotNull] LanguageParser.ParensContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogical([NotNull] LanguageParser.LogicalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Logical</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogical([NotNull] LanguageParser.LogicalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceAppend</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceAppend([NotNull] LanguageParser.SliceAppendContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceAppend</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceAppend([NotNull] LanguageParser.SliceAppendContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Booleano</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleano([NotNull] LanguageParser.BooleanoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Booleano</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleano([NotNull] LanguageParser.BooleanoContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Nilll</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNilll([NotNull] LanguageParser.NilllContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Nilll</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNilll([NotNull] LanguageParser.NilllContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MatrixAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrixAccess([NotNull] LanguageParser.MatrixAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MatrixAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrixAccess([NotNull] LanguageParser.MatrixAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructAccess([NotNull] LanguageParser.StructAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructAccess([NotNull] LanguageParser.StructAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivMod([NotNull] LanguageParser.MulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivMod([NotNull] LanguageParser.MulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceAssign([NotNull] LanguageParser.SliceAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceAssign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceAssign([NotNull] LanguageParser.SliceAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] LanguageParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] LanguageParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecimal([NotNull] LanguageParser.DecimalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decimal</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecimal([NotNull] LanguageParser.DecimalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] LanguageParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Number</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] LanguageParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructMethodCall</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructMethodCall([NotNull] LanguageParser.StructMethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructMethodCall</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructMethodCall([NotNull] LanguageParser.StructMethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Increment</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncrement([NotNull] LanguageParser.IncrementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Increment</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncrement([NotNull] LanguageParser.IncrementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] LanguageParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] LanguageParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceAccess([NotNull] LanguageParser.SliceAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceAccess</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceAccess([NotNull] LanguageParser.SliceAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Decrement</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecrement([NotNull] LanguageParser.DecrementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Decrement</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecrement([NotNull] LanguageParser.DecrementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceIndex</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceIndex([NotNull] LanguageParser.SliceIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceIndex</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceIndex([NotNull] LanguageParser.SliceIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] LanguageParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] LanguageParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CallFunc</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallFunc([NotNull] LanguageParser.CallFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CallFunc</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallFunc([NotNull] LanguageParser.CallFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Cadena</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCadena([NotNull] LanguageParser.CadenaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Cadena</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCadena([NotNull] LanguageParser.CadenaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelational([NotNull] LanguageParser.RelationalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelational([NotNull] LanguageParser.RelationalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot([NotNull] LanguageParser.NotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot([NotNull] LanguageParser.NotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Caracter</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaracter([NotNull] LanguageParser.CaracterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Caracter</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaracter([NotNull] LanguageParser.CaracterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SliceLen</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceLen([NotNull] LanguageParser.SliceLenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SliceLen</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceLen([NotNull] LanguageParser.SliceLenContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Assign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] LanguageParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Assign</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] LanguageParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegate([NotNull] LanguageParser.NegateContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="LanguageParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegate([NotNull] LanguageParser.NegateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.embebidaex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmbebidaex([NotNull] LanguageParser.EmbebidaexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.embebidaex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmbebidaex([NotNull] LanguageParser.EmbebidaexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] LanguageParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] LanguageParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LanguageParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTipo([NotNull] LanguageParser.TipoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LanguageParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTipo([NotNull] LanguageParser.TipoContext context);
}
} // namespace analyzer
